### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dineshrboson** [ichiro-its/ros2-build-debian-action#8]
Hi guys. I am using ROS melodic and would like to deploy my private ROS project that is currently in GitHub and passed all other ROS CI GitHub actions. Is there any simple way using GitHub actions to achieve this.

**Comment by threeal** [comment]
For ROS 1, you may use [this action](https://github.com/ros-tooling/action-ros-ci). It's possible to run that on private repository, but there's run limit for that.

**Comment by dineshrboson** [comment]
Yeah, I am using it on my project, but you know it can't be used for generating deb.

**Comment by threeal** [comment]
you could still follow [Bloom](https://bloom.readthedocs.io/en/0.5.10/) guide on creating Debian for ROS and integrate that on the GitHub Action. See [this](https://gist.github.com/awesomebytes/196eab972a94dd8fcdd69adfe3bd1152) on how to generate that locally, or you may see [scripts](https://github.com/ichiro-its/ros2-build-debian-action/tree/main/scripts) in this action too to generate that on GitHub Action.
